channels:
  - bioconda
  - conda-forge
  - defaults
  - jmcmurray
dependencies:
  - contextily
  - descartes
  - fiona==1.8.13
  - geopandas==0.8.1
  - json
  - matplotlib
  - notebook
  - pip
  - pip:
    - git+https://github.com/woodcrafty/PyETo.git
  - plotly
  - python
  - rasterio
  - rasterstats
  - scipy
  - xlrd
  