channels:
  - bioconda
  - conda-forge
  - defaults
  - jmcmurray
dependencies:
  - contextily
  - descartes
  - geopandas
  - json
  - matplotlib
  - notebook
  - plotly
  - python
  - rasterio
  - scipy
  - xlrd
  